### ISSUE TITLE
Throw descriptive error on invalid token

### ISSUE THREAD

**Issue by RubenVerborgh** [matthieubosquet/ts-dpop#14]
```
2020-11-26T20:09:33.436Z [DPoPWebIdExtractor] error: Error verifying WebID: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (buffer.js:331:9)
    at Object.exports.decode (/Users/ruben/Documents/UGent/Solid/solid-community-server/node_modules/jose/dist/node/cjs/runtime/base64url.js:11:34)
    at Object.webID (/Users/ruben/Documents/UGent/Solid/solid-community-server/node_modules/ts-dpop/dist/jwt.js:7:67)
    at Object.verify (/Users/ruben/Documents/UGent/Solid/solid-community-server/node_modules/ts-dpop/dist/access-token.js:30:83)
    at Object.verify (/Users/ruben/Documents/UGent/Solid/solid-community-server/node_modules/ts-dpop/dist/index.js:17:48)
    at DPoPWebIdExtractor.handle (/Users/ruben/Documents/UGent/Solid/solid-community-server/src/authentication/DPoPWebIdExtractor.js:25:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async AuthenticatedLdpHandler.runHandlers (/Users/ruben/Documents/UGent/Solid/solid-community-server/src/ldp/AuthenticatedLdpHandler.js:64:29)
    at async AuthenticatedLdpHandler.handle (/Users/ruben/Documents/UGent/Solid/solid-community-server/src/ldp/AuthenticatedLdpHandler.js:43:61)
    at async /Users/ruben/Documents/UGent/Solid/solid-community-server/src/server/ExpressHttpServerFactory.js:38:17 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by matthieubosquet** [comment]
Descriptive errors added all over.
