### ISSUE TITLE
Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by RubenVerborgh** [matthieubosquet/ts-dpop#16]
When logging in with inrupt.net, I get:

```
TypeError: Cannot read property 'startsWith' of undefined
    at RdfDereferencer.dereference (/Users/ruben/Documents/UGent/Solid/solid-community-server/node_modules/rdf-dereference/lib/RdfDereferencer.js:21:18)
    at Object.oidcIssuer (/Users/ruben/Documents/UGent/Solid/solid-community-server/node_modules/ts-dpop/dist/webid.js:11:67)
    at Object.verify (/Users/ruben/Documents/UGent/Solid/solid-community-server/node_modules/ts-dpop/dist/access-token.js:30:66)
    at Object.verify (/Users/ruben/Documents/UGent/Solid/solid-community-server/node_modules/ts-dpop/dist/index.js:17:48)
```

**Comment by matthieubosquet** [comment]
I added support for losely typed, non-spec compliant Access tokens.

- `client_webid` claim instead of `client_id` (ess broker)
- `sub` claim instead of `webid` (inrupt.net)

It should work if you update to 0.2.0 https://www.npmjs.com/package/ts-dpop

I only tested locally, so might have missed something.

**Comment by RubenVerborgh** [comment]
Gets me a

```
BadRequestHttpError: Error verifying WebID via DPoP token: Invalid OIDC Issuer Claim
    at DPoPWebIdExtractor.handle (/Users/ruben/Documents/UGent/Solid/solid-community-server/src/authentication/DPoPWebIdExtractor.js:38:19)
```

now

**Comment by matthieubosquet** [comment]
It should now be fixed.
